# Generated by Django 5.2.4 on 2025-07-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_expense_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('staff', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
